# Generated by Django 5.2.9 on 2025-12-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='seña',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='cancha_reservas_reserva',
        ),
    ]
