# Generated by Django 5.2.9 on 2025-12-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha_reservas', '0002_reserva_email_reserva_estado_alter_reserva_cancha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=20),
        ),
    ]
