# Generated by Django 5.2.9 on 2025-12-16 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha_reservas', '0003_remove_reserva_email_remove_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='seña',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
